stages:
  preprocess:
    cmd: python src/data/preprocess.py
    deps:
      - data/raw/student_scores.csv
    outs:
      - data/processed/train.csv

  train:
    cmd: python src/model/train.py
    deps:
      - data/processed/train.csv
    outs:
      - models/model_v1.pkl